import { AgentProvider } from '../providers/interface';
import { generateSystemPrompt } from './prompts';
import { SkillManager } from './skillManager';
import { get_encoding } from 'tiktoken';
import * as fs from 'fs';
import * as path from 'path';

// ─────────────────────────────────────────────────────────────────────────────
// MECHANICAL MEMORY WRITER
// Writes every project event DIRECTLY to ATCLI_MEMORY.md without relying on AI.
// This means the memory is ALWAYS accurate — even if AI skips a checkpoint.
// ─────────────────────────────────────────────────────────────────────────────
class MemoryWriter {
    private memPath: string;

    constructor(cwd: string) {
        this.memPath = path.join(cwd, 'ATCLI_MEMORY.md');
    }

    /** Ensure the memory file exists with a skeleton if it's brand new */
    private ensureFile(): void {
        if (!fs.existsSync(this.memPath)) {
            fs.writeFileSync(this.memPath, [
                '# ATCLI Project Memory',
                '> Auto-generated by ATCLI. System writes events mechanically. AI writes descriptions and summaries.',
                '',
                '## 📌 Project',
                '**Intent**: (captured from first user prompt)',
                '**Status**: In Progress',
                '**IDE**: (auto-detected)',
                '**Stack**: (AI to describe: language, framework, key libraries)',
                '',
                '## 📖 Project Summary',
                '> AI writes this: What is this project? What problem does it solve? Who is it for?',
                '> Example: "A SaaS landing page built with Next.js 14 + Tailwind + Framer Motion.',
                '>  Has hero, pricing, testimonials, FAQ, and contact form sections."',
                '',
                '## 📋 File Registry',
                '> Format: `path` [status] — what this file does (AI fills the description)',
                '',
                '## 📜 Change Log',
                '> Append-only. System writes timestamps. AI adds context where marked.',
                '',
                '## 🗑️ Deleted Files Log',
                '> System logs the file. AI fills the reason.',
                '',
                '## 💻 Commands Run',
                '',
                '## 📦 Packages Installed',
                '',
                '## 🔴 AECL Errors',
                '',
                '## ✅ Completed Features',
                '',
                '## 🔜 Next Steps',
                '',
                '## 🏗️ Architecture Notes',
                '> AI writes: key design decisions, patterns used, folder structure explanation',
            ].join('\n'), 'utf-8');
        }
    }

    /** Append a single line to a named section (creates section if missing) */
    private appendToSection(section: string, line: string): void {
        this.ensureFile();
        try {
            let content = fs.readFileSync(this.memPath, 'utf-8');
            const sectionHeader = `## ${section}`;
            const idx = content.indexOf(sectionHeader);
            if (idx === -1) {
                // Section doesn't exist — append to end
                content += `\n\n## ${section}\n${line}`;
            } else {
                // Find the end of this section (next ## or EOF)
                const afterHeader = idx + sectionHeader.length;
                const nextSectionMatch = content.slice(afterHeader).match(/\n## /);
                const insertAt = nextSectionMatch
                    ? afterHeader + nextSectionMatch.index!
                    : content.length;
                content = content.slice(0, insertAt) + '\n' + line + content.slice(insertAt);
            }
            fs.writeFileSync(this.memPath, content, 'utf-8');
        } catch { /* ignore write errors — never crash the agent */ }
    }

    /** Update a file entry in the File Registry section */
    private updateFileRegistry(filePath: string, status: string, note: string): void {
        this.ensureFile();
        try {
            let content = fs.readFileSync(this.memPath, 'utf-8');
            const sectionHeader = '## 📋 File Registry';
            const idx = content.indexOf(sectionHeader);
            if (idx === -1) {
                content += `\n\n${sectionHeader}\n- \`${filePath}\` [${status}] — ${note}`;
                fs.writeFileSync(this.memPath, content, 'utf-8');
                return;
            }
            const afterHeader = idx + sectionHeader.length;
            const nextSectionMatch = content.slice(afterHeader).match(/\n## /);
            const sectionEnd = nextSectionMatch ? afterHeader + nextSectionMatch.index! : content.length;
            const sectionBody = content.slice(afterHeader, sectionEnd);

            // Check if this file already has an entry
            const filePattern = new RegExp(`- \\\`${filePath.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\\`[^\\n]*`, 'g');
            const newEntry = `- \`${filePath}\` [${status}] — ${note}`;
            if (filePattern.test(sectionBody)) {
                // Update existing entry
                const updatedBody = sectionBody.replace(filePattern, newEntry);
                content = content.slice(0, afterHeader) + updatedBody + content.slice(sectionEnd);
            } else {
                // Append new entry
                content = content.slice(0, sectionEnd) + '\n' + newEntry + content.slice(sectionEnd);
            }
            fs.writeFileSync(this.memPath, content, 'utf-8');
        } catch { /* ignore */ }
    }

    private ts(): string {
        return new Date().toISOString().replace('T', ' ').substring(0, 19);
    }

    /** Track a file create event. Returns the filePath so caller can inject AI description prompt */
    onFileCreated(filePath: string): string {
        console.log(`\n📝 [Memory] Auto-logging: CREATED → ${filePath}`);
        // Placeholder: AI fills in the real description after writing the file
        this.updateFileRegistry(filePath, 'created', '[AI: describe what this file does in 1 sentence]');
        this.appendToSection('📜 Change Log', `- ${this.ts()} | ✅ CREATED \`${filePath}\` — [AI: add what this file does]`);
        return filePath;
    }

    /** Track a file modify/patch event */
    onFileModified(filePath: string, tool: string): void {
        console.log(`\n📝 [Memory] Auto-logging: MODIFIED → ${filePath}`);
        // Only update if the current note is a placeholder or 'newly created' — don't erase AI descriptions
        try {
            const content = fs.existsSync(this.memPath) ? fs.readFileSync(this.memPath, 'utf-8') : '';
            const escapedPath = filePath.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
            const existingEntry = content.match(new RegExp(`- \\\`${escapedPath}\\\`[^\\n]*`));
            const currentNote = existingEntry ? existingEntry[0] : '';
            // Only overwrite if it's still a system placeholder (AI hasn't described it yet)
            if (!currentNote || currentNote.includes('[AI:') || currentNote.includes('newly created') || currentNote.includes('last modified via')) {
                this.updateFileRegistry(filePath, 'modified', '[AI: update description with what changed]');
            } else {
                // File has a real description — just update the status tag, keep the description
                const newEntry = currentNote.replace(/\[(?:created|modified)\]/, '[modified]');
                if (newEntry !== currentNote) {
                    const updated = content.replace(currentNote, newEntry);
                    fs.writeFileSync(this.memPath, updated, 'utf-8');
                }
            }
        } catch { /* ignore */ }
        this.appendToSection('📜 Change Log', `- ${this.ts()} | ✏️  MODIFIED \`${filePath}\` (${tool})`);
    }

    /** Track a file delete event — also marks it in Deleted Files Log */
    onFileDeleted(filePath: string): void {
        console.log(`\n📝 [Memory] Auto-logging: DELETED → ${filePath}`);
        // Preserve existing AI description but mark as deleted
        try {
            const content = fs.existsSync(this.memPath) ? fs.readFileSync(this.memPath, 'utf-8') : '';
            const escapedPath = filePath.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
            const existingEntry = content.match(new RegExp(`- \\\`${escapedPath}\\\`[^\\n]*`));
            const existingDesc = existingEntry
                ? existingEntry[0].replace(/- `[^`]+` \[[^\]]+\] — /, '').trim()
                : '(no prior description)';
            this.updateFileRegistry(filePath, '~~DELETED~~', `❌ DELETED — was: ${existingDesc}`);
        } catch {
            this.updateFileRegistry(filePath, '~~DELETED~~', '❌ file was deleted');
        }
        this.appendToSection('📜 Change Log', `- ${this.ts()} | 🗑️  DELETED \`${filePath}\``);
        this.appendToSection('🗑️ Deleted Files Log', `- ${this.ts()} | \`${filePath}\` — reason: [AI to fill why it was deleted and if it will be rebuilt]`);
    }

    /** Track a terminal command */
    onCommandRun(command: string): void {
        console.log(`\n📝 [Memory] Auto-logging: COMMAND → ${command.substring(0, 60)}`);
        this.appendToSection('💻 Commands Run', `- ${this.ts()} | \`${command.substring(0, 120)}\``);
    }

    /** Track a package install */
    onPackageInstalled(packageName: string): void {
        console.log(`\n📝 [Memory] Auto-logging: INSTALL → ${packageName}`);
        this.appendToSection('📦 Packages Installed', `- ${this.ts()} | \`${packageName}\``);
    }

    /** Track an AECL error fix */
    onErrorFixed(filePath: string, errorMsg: string): void {
        this.appendToSection('📜 Change Log', `- ${this.ts()} | 🔧 FIXED \`${filePath}\` — ${errorMsg.substring(0, 100)}`);
    }
}

export class AgentLoop {
    private maxIterations = 500;
    private skillManager: SkillManager;
    public isAgenticaMode: boolean = false;
    private totalTokensProcessed: number = 0;
    private tokenizer = get_encoding("cl100k_base");
    // AECL: Mechanical edit counter (not prompt-based) to trigger aecl_check every 5 file writes
    private editsSinceLastAeclCheck: number = 0;
    private readonly AECL_CHECK_INTERVAL = 5;
    // PROJECT INTENT: Stores the user's original project description for intelligent decision-making
    private projectIntent: string = '';
    // FILE REGISTRY: Tracks every file operation this session for memory and change log
    private fileRegistry: Map<string, { status: 'created' | 'modified' | 'deleted'; changes: string[]; timestamp: string }> = new Map();

    constructor(private provider: AgentProvider, private isFirstMessage: boolean = false) {
        this.skillManager = new SkillManager();
    }

    public async run(userMessage: string): Promise<void> {
        // Reset file registry at each run() to prevent bleed between messages
        this.fileRegistry = new Map();
        const cwd = process.cwd();
        const memoryPath = path.join(cwd, 'ATCLI_MEMORY.md');
        // Mechanical memory writer — writes directly to ATCLI_MEMORY.md for EVERY event
        const memWriter = new MemoryWriter(cwd);
        let bootMemoryContent = '';
        if (fs.existsSync(memoryPath)) {
            try {
                bootMemoryContent = fs.readFileSync(memoryPath, 'utf-8');
                console.log(`\n📖 [ATCLI Memory] Loaded ATCLI_MEMORY.md (${bootMemoryContent.length} chars) from project.`);
            } catch(e) { /* ignore */ }
        } else {
            console.log(`\n📝 [ATCLI Memory] No ATCLI_MEMORY.md found — will be created during this session.`);
        }

        // IDE Detection: Check for IDE-specific config folders
        const ideMarkers: Record<string, string> = {
            '.vscode': 'VS Code',
            '.idea': 'JetBrains IDE (IntelliJ/WebStorm/PyCharm)',
            '.cursor': 'Cursor AI IDE',
            '.zed': 'Zed Editor',
        };
        let detectedIDE = 'Unknown IDE';
        for (const [marker, ideName] of Object.entries(ideMarkers)) {
            if (fs.existsSync(path.join(cwd, marker))) {
                detectedIDE = ideName;
                break;
            }
        }
        (global as any).ATCLI_DETECTED_IDE = detectedIDE;
        console.log(`\n🖥️  [IDE Detection] Detected: ${detectedIDE}`);

        // Capture the user's original message as the Project Intent
        this.projectIntent = userMessage.substring(0, 2000);
        (global as any).ATCLI_PROJECT_INTENT = this.projectIntent;
        console.log(`\n📌 [Project Intent Captured] (${this.tokenizer.encode(this.projectIntent).length} tokens)`);

        if (this.isAgenticaMode) {
            this.maxIterations = 5000; // Agentica continuous execution allows far more iterations
            console.log(`\n🤖 Starting Agentica OpenClaw Continuous Loop (Max Iterations: ${this.maxIterations})...`);
        } else {
            console.log(`\n🤖 Starting Autonomous Agent Loop (Max Iterations: ${this.maxIterations})...`);
        }
        
        // Dynamically load all built-in and user workspace skills
        await this.skillManager.loadAllSkills();

        // Construct the initial prompt injecting the system instructions
        const systemPrompt = await generateSystemPrompt(this.skillManager, this.isAgenticaMode);
        let currentMessage = "";

        // Boot injection: Project Intent + IDE context + Memory — included in ALL branches
        const bootInjection = [
            `[PROJECT INTENT]: ${this.projectIntent}`,
            `[IDE CONTEXT]: User is working in ${detectedIDE}. Always generate IDE-compatible configs (e.g., .vscode/settings.json for VS Code, not .idea/ configs). Do NOT write configs for other IDEs unless the user explicitly asks.`,
            bootMemoryContent
                ? `[ATCLI PROJECT MEMORY - READ THIS FIRST]:\n${bootMemoryContent.substring(0, 3000)}\n[END OF MEMORY]`
                : '[ATCLI PROJECT MEMORY]: No prior memory found. This is a fresh start. You will create ATCLI_MEMORY.md at your first episodic checkpoint.'
        ].join('\n\n');

        if (this.isFirstMessage) {
            const MAX_CHUNK_LENGTH = 100000; // Increased to 100k to prevent splitting JSON definitions across chunks
            
            if (systemPrompt.length > MAX_CHUNK_LENGTH) {
                console.log(`\n[Agent] System prompt is massive (${systemPrompt.length} chars). Intelligently splitting into semantic chunks...`);
                
                // Semantic chunking: split by paragraphs (handle both LF and CRLF) to avoid breaking tool JSONs or security rules in half
                const paragraphs = systemPrompt.split(/\r?\n\r?\n/);
                const chunks: string[] = [];
                let currentChunkText = "";
                
                for (const p of paragraphs) {
                    if (currentChunkText.length + p.length + 2 > MAX_CHUNK_LENGTH) {
                        if (currentChunkText) chunks.push(currentChunkText.trim());
                        currentChunkText = p;
                    } else {
                        currentChunkText += (currentChunkText ? '\n\n' : '') + p;
                    }
                }
                if (currentChunkText) chunks.push(currentChunkText.trim());

                const numChunks = chunks.length;
                for (let i = 0; i < numChunks; i++) {
                    const isLastChunk = i === numChunks - 1;
                    const chunkText = chunks[i];
                    
                    let messageToSend = `[System Knowledge Base Part ${i + 1}/${numChunks}]\n${chunkText}`;
                    
                    if (!isLastChunk) {
                        messageToSend += `\n\n[SYSTEM INSTRUCTION: This is a partial knowledge base. Do not execute the user request yet. Just reply "Received part ${i + 1}".]`;
                        console.log(`[Agent] Sending system knowledge chunk ${i + 1}/${numChunks}...`);
                        const chunkResponse = await this.provider.sendMessage(messageToSend);
                        if (chunkResponse.error) {
                            console.log(`❌ Provider Error during chunking: ${chunkResponse.error}`);
                            return;
                        }
                    } else {
                        // The final chunk will be passed into the main loop along with the actual user request
                        console.log(`[Agent] Sending final chunk ${i + 1}/${numChunks} with actual user request...`);
                        currentMessage = `${messageToSend}\n\nUser Request:\n${userMessage}\n\n${bootInjection}`;
                    }
                }
            } else {
                currentMessage = `${systemPrompt}\n\nUser Request:\n${userMessage}\n\n${bootInjection}`;
            }
        } else {
            let reminder = "[SYSTEM REMINDER: DO NOT ASK FOR PERMISSION. DO NOT WRITE JAVASCRIPT CODE BLOCKS. IF YOU NEED TO EXECUTE A COMMAND OR FILE OPERATION, OUTPUT THE <tool_call> XML BLOCK. IF THE USER IS JUST CHATTING, YOU MAY RESPOND WITH TEXT NORMALLY.]";
            if (this.isAgenticaMode) {
                reminder += "\n[AGENTICA OVERRIDE: YOU ARE CONNECTED TO THE ATCLI XML BRIDGE. YOU DO HAVE PHYSICAL PC CONTROL. YOU MUST NOT USE INTERNAL SEARCH. EMIT <tool_call> TO OPEN THE BROWSER OR RUN COMMANDS.]";
            }
            currentMessage = `${userMessage}\n\n${reminder}\n\n${bootInjection}`;
        }
        
        let lastRefreshTokens = this.totalTokensProcessed;

        for (let i = 1; i <= this.maxIterations; i++) {
            
            // Dynamic Context Refresh Threshold (Browser AI has ~128k-200k, Local AI usually 32k)
            const isLocal = this.provider.id === 'ollama' || this.provider.id === 'local' || this.provider.id === 'qwen-local';
            const refreshThreshold = isLocal ? 20000 : 80000;
            
            // CONTEXT REFRESH: Re-inject tools + Project Intent + Memory Snapshot to prevent memory loss
            if (this.totalTokensProcessed - lastRefreshTokens > refreshThreshold) {
                console.log(`\n🔄 [Agent] Context window approaching (${refreshThreshold} tokens). Auto-resending System Prompt + Intent + Memory...`);
                const intentSection = this.projectIntent 
                    ? `\n\n[PROJECT INTENT RE-INJECTION: The user's original goal is:\n"${this.projectIntent}"\nStay strictly aligned to this. Do not add unrequested features or delete files not related to this goal.]`
                    : '';
                // Re-read ATCLI_MEMORY.md at refresh time for latest state
                let liveMemorySnapshot = '';
                if (fs.existsSync(memoryPath)) {
                    try {
                        const memContent = fs.readFileSync(memoryPath, 'utf-8');
                        liveMemorySnapshot = `\n\n[LIVE ATCLI_MEMORY.md SNAPSHOT (auto-read at context refresh):\n${memContent.substring(0, 2000)}\n]`;
                    } catch(e) { /* ignore */ }
                }
                const ideSection = `\n\n[IDE CONTEXT REMINDER]: User is in ${detectedIDE}. Write IDE-appropriate configs only.`;
                currentMessage = `[CONTEXT REFRESH (${refreshThreshold} Context Protection): Re-injecting tools + project state to prevent memory loss.]\n\n${systemPrompt}${intentSection}${liveMemorySnapshot}${ideSection}\n\n[END OF CONTEXT REFRESH]\n\n${currentMessage}`;
                lastRefreshTokens = this.totalTokensProcessed;
            }

            // ATCLI_MEMORY 3-Iteration Recall Check
            if (i > 1 && i % 3 === 0) {
                currentMessage += `\n\n[SYSTEM INTELLIGENT RECALL: You have been running for 3 iterations. To prevent task hallucination, you MUST immediately use the grep_search tool or view_file tool to check your ATCLI_MEMORY.md or global instructions before writing any more code. Stay on track!]`;
            }

            // Active Background Task Reminder (Prevents forgetting status)
            const globalTasks = (global as any).ATCLI_TASKS;
            if (globalTasks && globalTasks.size > 0) {
                const taskIds = Array.from(globalTasks.keys()).join(', ');
                currentMessage += `\n\n<CRITICAL_SYSTEM_REMINDER>\n<TASKS_RUNNING>${taskIds}</TASKS_RUNNING>\n<ACTION_REQUIRED>Do NOT forget to use the 'manage_task' tool with sub_action="logs" or "status" to check if they crashed or finished! Context loss prevention is active.</ACTION_REQUIRED>\n</CRITICAL_SYSTEM_REMINDER>\n`;
            }

            console.log(`\n[Agent Iteration ${i}/${this.maxIterations}] Sending message...`);
            
            this.totalTokensProcessed += this.tokenizer.encode(currentMessage).length;
            (global as any).atcli_current_tokens = this.totalTokensProcessed;
            
            let response;
            if ((this as any).pendingVisionImage) {
                const imagePath = (this as any).pendingVisionImage;
                (this as any).pendingVisionImage = null; // reset
                response = await this.provider.sendImageAndMessage(imagePath, currentMessage);
            } else {
                response = await this.provider.sendMessage(currentMessage);
            }
            
            if (response.error) {
                // Suppress expected errors during graceful shutdown
                if (!response.error.includes('Target page, context or browser has been closed')) {
                    console.log(`❌ Provider Error: ${response.error}`);
                }
                break;
            }

            const aiText = response.text;
            this.totalTokensProcessed += this.tokenizer.encode(aiText).length;
            (global as any).atcli_current_tokens = this.totalTokensProcessed;
            
            console.log(`\n📊 Exact Context Usage: ${this.totalTokensProcessed.toLocaleString()} Tokens`);
            console.log(`\n[AI RESPONSE]:\n${aiText}`);

            // Parse tool call
            let toolCall;
            try {
                toolCall = this.parseToolCall(aiText);
            } catch (err: any) {
                console.log(`\n⚠️ Tool Parsing Error: ${err.message}`);
                currentMessage = `<tool_result>\nFailed to parse JSON inside <tool_call>: ${err.message}. Please fix your JSON syntax (e.g. escape inner double quotes with \\\") and try again.\n</tool_result>\n[SYSTEM REMINDER: What is your next step? DO NOT ASK FOR PERMISSION. IMMEDIATELY OUTPUT THE NEXT <tool_call> XML BLOCK. 24/7 SECURITY FIREWALL ACTIVE: You are strictly forbidden from running destructive commands.]`;
                continue;
            }
            
            if (!toolCall) {
                // No tool call found, meaning the AI has finished its task
                if (aiText.includes('@TRIGGER_FINAL_AUDIT')) {
                    console.log(`\n🎉 Project completion detected! Spawning Tech Lead Auditor...`);
                    const { ManagerLoop } = require('./manager');
                    const manager = new ManagerLoop(this.provider, true);
                    manager.isAgenticaMode = this.isAgenticaMode; // Pass the autonomy status to the manager
                    await manager.run('Perform a full deep architectural and bug audit on the entire codebase using all your available auditing skills. Fix any bugs found.');
                } else {
                    console.log(`\n✅ Agent task completed or requires user feedback.`);
                }
                break;
            }

            // ─── SMART SAFETY GATE ───────────────────────────────────────────
            // Tier 1: HARD BLOCK — never allow these (system-destruction level)
            const hardBlockedTools = ['clear_workspace', 'install_skill'];
            
            // Tier 2: SOFT BLOCK — run_command and run_background_command need user approval
            const softBlockedTools = ['run_command', 'run_background_command'];

            // Tier 3: SMART DELETE — delete_file allowed if ALL paths are inside CWD
            // Blocked if any path tries to escape the project folder
            if (toolCall.action === 'delete_file') {
                const pathsToCheck = toolCall.paths || (toolCall.path ? [toolCall.path] : []);
                const cwd = process.cwd();
                const escapingPaths = pathsToCheck.filter((p: string) => {
                    const resolved = require('path').resolve(cwd, p);
                    return !resolved.startsWith(cwd);
                });
                
                if (escapingPaths.length > 0) {
                    // HARD BLOCK: trying to delete outside project folder
                    console.log(`\n🚫 [ATCLI SECURITY] Blocked delete_file — paths escape the project folder:`);
                    escapingPaths.forEach((p: string) => console.log(`   ❌ ${p}`));
                    currentMessage = `<tool_result>\n[SECURITY BLOCK] Cannot delete files outside the current project folder: ${escapingPaths.join(', ')}\n</tool_result>\n[SYSTEM REMINDER: DO NOT attempt to delete files outside the current project directory. Adjust your plan.]`;
                    continue;
                } else {
                    // SMART ALLOW: within project — show info but auto-allow in Agentica, ask in Vibecoding
                    console.log(`\n🗑️  [ATCLI] AI wants to delete (within project):`);
                    pathsToCheck.forEach((p: string) => console.log(`   📄 ${p}`));
                    
                    if (!this.isAgenticaMode) {
                        const rawAnswer = await (global as any).askQuestion('Allow delete? (Y/n/feedback): ');
                        const answer = rawAnswer.trim().toLowerCase();
                        if (answer === 'n' || answer === 'no') {
                            console.log(`\n🚫 Delete rejected by user.`);
                            currentMessage = `<tool_result>\nUser denied the delete operation.\n</tool_result>\n[SYSTEM REMINDER: The user rejected this delete. Find an alternative approach — perhaps just rewrite the file content instead of deleting it. IMMEDIATELY OUTPUT THE NEXT <tool_call> XML BLOCK.]`;
                            continue;
                        } else if (answer !== 'y' && answer !== 'yes' && answer !== '') {
                            currentMessage = `<tool_result>\nUser feedback on delete: ${rawAnswer.trim()}\n</tool_result>\n[SYSTEM REMINDER: Adjust your approach based on this feedback. IMMEDIATELY OUTPUT THE NEXT <tool_call> XML BLOCK.]`;
                            continue;
                        }
                    }
                    // INTELLIGENT REBUILD DECISION: Inject Project Intent so AI decides whether to rebuild
                    console.log(`\n⚙️ Executing Skill: delete_file`);
                    const deleteResult = await this.skillManager.executeSkill('delete_file', toolCall);
                    console.log(`[Skill Output]: ${deleteResult}`);
                    const deletedFiles = pathsToCheck.join(', ');
                    const intentContext = this.projectIntent
                        ? `\n\n[PROJECT INTENT]: The user originally asked for: "${this.projectIntent.substring(0, 500)}"`
                        : '';
                    currentMessage = `<tool_result>\n${deleteResult}\n</tool_result>${intentContext}\n\n[INTELLIGENT DELETE DECISION REQUIRED]: You just deleted: ${deletedFiles}.\nThe system has already logged this deletion to ATCLI_MEMORY.md automatically.\n\nYou MUST now do TWO things:\n\n1. UPDATE the delete reason in ATCLI_MEMORY.md: Find the line\n   \`- ... | \`${deletedFiles}\` — reason: (AI will fill in why)\`\n   and use the replace tool to update it with the REAL reason, e.g.:\n   \`- ... | \`${deletedFiles}\` — reason: bad TypeScript types, rebuilt as X\`\n\n2. REBUILD OR SKIP based on Project Intent:\n  - If this file IS needed for the project → IMMEDIATELY recreate it with write_file.\n  - If this file is NOT needed → clean up imports and continue.\n\nOutput your replace tool_call for the memory reason FIRST, then your rebuild or continue decision.`;
                    continue;
                }
            }

            if (hardBlockedTools.includes(toolCall.action)) {
                console.log(`\n⚠️  [ATCLI Safety] The AI wants to execute: ${toolCall.action}`);
                console.log(`Arguments: ${JSON.stringify(toolCall, null, 2)}`);
                if (this.isAgenticaMode) {
                    console.log(`\n🛡️ [Agentica Autonomy] Auto-approving.`);
                } else {
                    const rawAnswer = await (global as any).askQuestion('Allow this action? (Y/n/feedback): ');
                    const answer = rawAnswer.trim().toLowerCase();
                    if (answer === 'n' || answer === 'no') {
                        console.log(`\n🚫 Action rejected by user.`);
                        currentMessage = `<tool_result>\nUser denied permission.\n</tool_result>\n[SYSTEM REMINDER: What is your next step? DO NOT ASK FOR PERMISSION. IMMEDIATELY OUTPUT THE NEXT <tool_call> XML BLOCK.]`;
                        continue;
                    } else if (answer !== 'y' && answer !== 'yes' && answer !== '') {
                        console.log(`\n💬 Sending user feedback to AI...`);
                        currentMessage = `<tool_result>\nUser rejected with feedback: ${rawAnswer.trim()}\n</tool_result>\n[SYSTEM REMINDER: Correct your tool call based on the user's feedback. IMMEDIATELY OUTPUT THE NEXT <tool_call> XML BLOCK.]`;
                        continue;
                    }
                }
            }

            if (softBlockedTools.includes(toolCall.action)) {
                console.log(`\n⚠️  [ATCLI Safety] The AI wants to run a command:`);
                const cmdDisplay = toolCall.command || toolCall.cmd || JSON.stringify(toolCall);
                console.log(`   > ${cmdDisplay}`);
                if (this.isAgenticaMode) {
                    console.log(`\n🛡️ [Agentica Autonomy] Auto-approving command.`);
                } else {
                    const rawAnswer = await (global as any).askQuestion('Run this command? (Y/n/feedback): ');
                    // Fix: trim fully, take first char only to avoid 'yy' double-type issues
                    const answer = rawAnswer.trim().toLowerCase();
                    const firstChar = answer.charAt(0);
                    if (firstChar === 'n') {
                        console.log(`\n🚫 Command rejected.`);
                        currentMessage = `<tool_result>\nUser denied the command.\n</tool_result>\n[SYSTEM REMINDER: The user rejected this command. Try a safer alternative. IMMEDIATELY OUTPUT THE NEXT <tool_call> XML BLOCK.]`;
                        continue;
                    } else if (firstChar !== 'y' && answer !== '') {
                        console.log(`\n💬 Sending user feedback to AI...`);
                        currentMessage = `<tool_result>\nUser feedback: ${rawAnswer.trim()}\n</tool_result>\n[SYSTEM REMINDER: Adjust your approach. IMMEDIATELY OUTPUT THE NEXT <tool_call> XML BLOCK.]`;
                        continue;
                    }
                    // 'y', 'yes', 'yy', '' (Enter) all treated as approval
                    console.log(`\n✅ Command approved.`);
                }
            }

            console.log(`\n⚙️ Executing Skill: ${toolCall.action}`);

            // ─── SMART WRITE INTERCEPTOR ────────────────────────────────────────────
            // If AI uses write_file or create_file on an EXISTING file, redirect to replace
            if ((toolCall.action === 'write_file' || toolCall.action === 'create_file') && toolCall.path) {
                const targetPath = path.resolve(cwd, toolCall.path);
                if (fs.existsSync(targetPath)) {
                    console.log(`\n⚠️  [Smart Write] File already exists: ${toolCall.path}`);
                    console.log(`⚠️  [Smart Write] Full overwrite detected. Redirecting AI to use replace...`);
                    // Still execute (don't block) but inject a strong redirect note into result
                    const existingContent = (() => {
                        try { return fs.readFileSync(targetPath, 'utf-8').split('\n').slice(0, 8).join('\n') + '\n...'; }
                        catch { return '(could not read)'; }
                    })();
                    // Skip write_file, tell AI to use replace instead
                    const redirectMsg = `[SMART WRITE INTERCEPTOR]: The file '${toolCall.path}' already EXISTS in the project.\n\nCurrent file begins with:\n${existingContent}\n\nFull overwrite with write_file is INEFFICIENT and RISKY (loses existing working code).\nYou MUST use the 'replace' tool to update only the specific lines/sections that need changing.\nDO NOT use write_file on existing files. Use replace with the exact search and replace strings.\n\nIf you need to completely redesign this file, first read it with read_file, then use replace for each section.`;
                    currentMessage = `<tool_result>\n${redirectMsg}\n</tool_result>\n[SYSTEM REMINDER: Use replace tool for existing files. IMMEDIATELY OUTPUT A replace <tool_call> XML BLOCK.]`;
                    continue;
                }
            }

            let result = await this.skillManager.executeSkill(toolCall.action, toolCall);

            // AECL MECHANICAL COUNTER: Track file-writing tools and trigger aecl_check every 5 edits
            // NOTE: actual skill names are 'replace' (edit.ts) and 'append_content' (edit.ts), 'write_file' (fs_write.ts)
            const fileWritingTools = ['write_file', 'replace', 'append_content', 'create_file'];
            if (fileWritingTools.includes(toolCall.action)) {
                // FILE REGISTRY: Track every file operation for the change log
                const affectedPath = toolCall.path || toolCall.file || '';
                if (affectedPath) {
                    const ts = new Date().toISOString();
                    const isNew = !this.fileRegistry.has(affectedPath);
                    const action = toolCall.action === 'write_file' ? (isNew ? 'created' : 'modified') :
                                   toolCall.action === 'replace' ? 'modified' :
                                   toolCall.action === 'append_content' ? 'modified' : 'created';
                    const entry = this.fileRegistry.get(affectedPath) || { status: action as 'created' | 'modified' | 'deleted', changes: [] as string[], timestamp: ts };
                    entry.status = action as 'created' | 'modified' | 'deleted';
                    (entry.changes as string[]).push(`[${ts}] ${toolCall.action}`);
                    this.fileRegistry.set(affectedPath, entry);

                    // MECHANICAL MEMORY WRITE — directly updates ATCLI_MEMORY.md right now
                    if (action === 'created') {
                        memWriter.onFileCreated(affectedPath);
                        // Inject semantic prompt: AI MUST fill in what the file does in ATCLI_MEMORY.md
                        result += `\n\n[ATCLI MEMORY ENRICHMENT]: The system just logged \`${affectedPath}\` to ATCLI_MEMORY.md as [created].\nThe File Registry entry currently says "[AI: describe what this file does in 1 sentence]".\nYou MUST now use the replace tool to update that placeholder with a REAL 1-sentence description.\nExample: \`${affectedPath}\` [created] — Hero section component with gradient background and animated CTA button\nAlso update the 📖 Project Summary section if this is one of the first files (write what this project is building).`;
                    } else {
                        memWriter.onFileModified(affectedPath, toolCall.action);
                    }
                }

                this.editsSinceLastAeclCheck++;
                console.log(`\n📝 [AECL Counter] ${this.editsSinceLastAeclCheck}/${this.AECL_CHECK_INTERVAL} file writes since last check.`);
                if (this.editsSinceLastAeclCheck >= this.AECL_CHECK_INTERVAL) {
                    this.editsSinceLastAeclCheck = 0;
                    console.log(`\n🔍 [AECL] Auto-triggering error check after ${this.AECL_CHECK_INTERVAL} file writes...`);
                    const aeclResult = await this.skillManager.executeSkill('aecl_check', {
                        action: 'aecl_check',
                        files_written: Array.from(this.fileRegistry.keys()),
                        ai_notes: '[Auto-triggered by system after 5 file writes]'
                    });
                    console.log(`[AECL Auto-Check Result]:\n${aeclResult.substring(0, 500)}`);
                    result = result + `\n\n[AECL AUTO-CHECK TRIGGERED]:\n${aeclResult}`;
                }
            }

            // Track deletes in file registry + MECHANICAL MEMORY WRITE
            if (toolCall.action === 'delete_file') {
                const deletedPaths = toolCall.paths || (toolCall.path ? [toolCall.path] : []);
                for (const p of deletedPaths) {
                    const ts = new Date().toISOString();
                    this.fileRegistry.set(p, { status: 'deleted', changes: [`[${ts}] delete_file`], timestamp: ts });
                    // Write directly to memory file NOW — no AI needed
                    memWriter.onFileDeleted(p);
                }
            }

            // Track commands run + packages installed
            if (toolCall.action === 'run_command' || toolCall.action === 'run_background_command') {
                const cmd = toolCall.command || toolCall.cmd || '';
                if (cmd) {
                    memWriter.onCommandRun(cmd);
                    // Detect npm/pip installs
                    const installMatch = cmd.match(/(?:npm install|npm i|pip install|yarn add|pnpm add)\s+([\w@/\-\.]+)/i);
                    if (installMatch) memWriter.onPackageInstalled(installMatch[1]);
                }
            }

            // Global safety truncation to prevent web UI crashes from massive outputs
            if (result.length > 30000 && !result.startsWith('__ATCLI_VISION_PAYLOAD__')) {
                console.log(`[Warning]: Tool output truncated from ${result.length} to 30000 chars.`);
                result = result.substring(0, 30000) + "\n\n...[TRUNCATED: Output too large. Use read_lines or grep_search to read specific parts]...";
            }
            
            console.log(`[Skill Output]:\n${result.substring(0, 1000)}${result.length > 1000 ? '...' : ''}`);

            // Handle Native Vision Payload Interception
            if (result.startsWith('__ATCLI_VISION_PAYLOAD__')) {
                const parts = result.split('__');
                if (parts.length >= 3) {
                    const imagePath = parts[2];
                    const prompt = parts.slice(3).join('__');
                    // Store the vision payload to be sent at the START of the next iteration
                    (this as any).pendingVisionImage = imagePath;
                    (this as any).pendingVisionMessage = `<tool_result>\nVision payload attached.\n</tool_result>\n[SYSTEM REMINDER: ${prompt}]`;
                    currentMessage = (this as any).pendingVisionMessage;
                }
            } else {
                // Format the standard result to send back to the AI
                currentMessage = `<tool_result>\n${result}\n</tool_result>\n[SYSTEM REMINDER: What is your next step? DO NOT ASK FOR PERMISSION. IMMEDIATELY OUTPUT THE NEXT <tool_call> XML BLOCK. 24/7 SECURITY FIREWALL ACTIVE: You are strictly forbidden from running destructive commands. DO NOT CONVERSE.]`;
            }
            
            // Episodic Memory Checkpoint every 3 iterations
            if (i > 0 && i % 3 === 0) {
                console.log(`\n🧠 [EPISODIC MEMORY CHECKPOINT] Requesting structured memory save (iteration ${i})...`);
                
                // Build live file registry summary from this session
                const registrySummary = (() => {
                    if (this.fileRegistry.size === 0) return '(No files written yet this session)';
                    const lines: string[] = [];
                    for (const [filePath, entry] of this.fileRegistry.entries()) {
                        const icon = entry.status === 'created' ? '🆕' : entry.status === 'deleted' ? '🗑️' : '✏️';
                        lines.push(`${icon} \`${filePath}\` [${entry.status}] — ${entry.changes.length} op(s)`);
                    }
                    return lines.join('\n');
                })();

                // Scan memory file for unfilled AI placeholders
                const unfilledPlaceholders = (() => {
                    try {
                        const content = fs.existsSync(memoryPath) ? fs.readFileSync(memoryPath, 'utf-8') : '';
                        const matches = content.match(/\[AI:[^\]]+\]/g) || [];
                        return matches.length > 0
                            ? `\n\nUNFILLED PLACEHOLDERS FOUND (${matches.length}):\n${matches.slice(0, 10).map(m => `  • ${m}`).join('\n')}`
                            : '\n\n✅ No unfilled placeholders — all descriptions complete!';
                    } catch { return ''; }
                })();

                currentMessage += `\n\n[EPISODIC MEMORY CHECKPOINT — Iteration ${i}]:
The system has automatically tracked all file operations this session.

LIVE FILE REGISTRY (system-generated):
${registrySummary}
${unfilledPlaceholders}

You MUST now do the following using the replace tool on ATCLI_MEMORY.md:

━━━ TASK 1: FILL UNFILLED DESCRIPTIONS ━━━
For every line in the File Registry that says "[AI: describe what this file does in 1 sentence]",
replace it with what the file ACTUALLY does. Be specific:
  ✅ GOOD: "src/Hero.tsx [created] — Animated hero section with gradient, headline, and 'Get Started' CTA"
  ❌ BAD:  "src/Hero.tsx [created] — newly created"

━━━ TASK 2: UPDATE PROJECT SUMMARY ━━━
In the "## 📖 Project Summary" section, write (or update) a clear overview:
  - What is this project building?
  - What is the tech stack? (e.g. Next.js 14 + TypeScript + Tailwind + Framer Motion)
  - What sections/features exist so far?
  - Who is this for?

━━━ TASK 3: FILL DELETE REASONS ━━━
For any deleted files with "[AI to fill why...]", replace with the real reason:
  ✅ GOOD: "src/old-helper.ts — deleted: unused, no code referenced it. NOT rebuilt."
  ✅ GOOD: "src/Button.tsx — deleted: had wrong types. Rebuilt as src/ui/Button.tsx with generic props."

━━━ TASK 4: UPDATE 📌 PROJECT HEADER ━━━
Update:
  **Intent**: ${this.projectIntent.substring(0, 200)}
  **IDE**: ${detectedIDE}
  **Status**: [In Progress / Complete / Blocked]
  **Stack**: [list the actual tech stack you used]

RULES:
- Use replace tool to update EACH section individually (never write_file the whole thing)
- The Change Log and File Registry are append-only — do NOT delete old entries
- Do this BEFORE writing any more code!]`;
            }

            // True Context Window Refresh (Only if exceeding massive token limits)
            if (this.totalTokensProcessed > 180000) {
                console.log(`\n🔄 [CRITICAL CONTEXT REFRESH] 180k Token limit reached. Reinjecting full System Prompt to prevent memory loss.`);
                const refreshPrompt = await generateSystemPrompt(this.skillManager, this.isAgenticaMode);
                const MAX_CHUNK_LENGTH = 100000;
                
                if (refreshPrompt.length > MAX_CHUNK_LENGTH) {
                    const paragraphs = refreshPrompt.split(/\r?\n\r?\n/);
                    const chunks: string[] = [];
                    let currentChunkText = "";
                    for (const p of paragraphs) {
                        if (currentChunkText.length + p.length + 2 > MAX_CHUNK_LENGTH) {
                            if (currentChunkText) chunks.push(currentChunkText.trim());
                            currentChunkText = p;
                        } else {
                            currentChunkText += (currentChunkText ? '\n\n' : '') + p;
                        }
                    }
                    if (currentChunkText) chunks.push(currentChunkText.trim());

                    const numChunks = chunks.length;
                    for (let j = 0; j < numChunks; j++) {
                        const isLastChunk = j === numChunks - 1;
                        let messageToSend = `[CONTEXT REFRESH Part ${j + 1}/${numChunks}]\n${chunks[j]}`;
                        
                        if (!isLastChunk) {
                            messageToSend += `\n\n[SYSTEM INSTRUCTION: This is a partial context refresh. Do not execute anything yet. Just reply "Received refresh part ${j + 1}".]`;
                            console.log(`[Agent] Sending refresh chunk ${j + 1}/${numChunks}...`);
                            await this.provider.sendMessage(messageToSend);
                        } else {
                            // On the last chunk, append the actual current tool result we were trying to send!
                            currentMessage = `${messageToSend}\n\n[END OF CONTEXT REFRESH]\n\n${currentMessage}`;
                        }
                    }
                } else {
                    currentMessage = `[CONTEXT REFRESH: Core programming reminder:]\n\n${refreshPrompt}\n\n[END OF CONTEXT REFRESH]\n\n${currentMessage}`;
                }
                
                // Reset tracker to prevent infinite refresh looping
                this.totalTokensProcessed = 0;
                (global as any).atcli_current_tokens = 0;
            }
        }
    }

    private parseToolCall(text: string): any | null {
        // Look for <tool_call> ... </tool_call>
        const match = text.match(/<tool_call>([\s\S]*?)<\/tool_call>/);
        if (!match) return null; // No tool call means conversational response

        // Remove markdown code block syntax if the AI included it (e.g., ```json ... ```)
        let jsonStr = match[1].trim();
        if (jsonStr.startsWith('```json')) jsonStr = jsonStr.substring(7);
        else if (jsonStr.startsWith('```')) jsonStr = jsonStr.substring(3);
        if (jsonStr.endsWith('```')) jsonStr = jsonStr.substring(0, jsonStr.length - 3);
        
        jsonStr = jsonStr.trim();

        // Custom robust auto-fix for write_file tool which often contains unescaped quotes/newlines
        if (jsonStr.includes('"write_file"')) {
            const contentRegex = /"content"\s*:\s*"([\s\S]*)"\s*}/;
            const contentMatch = jsonStr.match(contentRegex);
            if (contentMatch) {
                let rawContent = contentMatch[1];
                // Unescape first to avoid double escaping if the AI partially escaped it
                rawContent = rawContent
                    .replace(/\\"/g, '"')
                    .replace(/\\n/g, '\n')
                    .replace(/\\r/g, '\r')
                    .replace(/\\t/g, '\t')
                    .replace(/\\\\/g, '\\');
                
                // Re-escape perfectly for JSON
                let safeContent = rawContent
                    .replace(/\\/g, '\\\\')
                    .replace(/"/g, '\\"')
                    .replace(/\n/g, '\\n')
                    .replace(/\r/g, '\\r')
                    .replace(/\t/g, '\\t');
                
                // Replace the broken content with the perfectly escaped content
                jsonStr = jsonStr.replace(contentRegex, `"content": "${safeContent}"}`);
            }
        }
        
        // Auto-fix unescaped backslashes (common when AI outputs Windows paths like C:\Users)
        // This regex replaces \ with \\ ONLY if it's not part of a valid JSON escape sequence like \n or \t
        jsonStr = jsonStr.replace(/\\([^"\\/bfnrtu])/g, '\\\\$1');
        
        // Let JSON.parse throw if invalid, so the loop can catch it and feed it back to the AI
        const parsed = JSON.parse(jsonStr);
        return parsed;
    }
}
